### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by alexandru-dinu** [alexandru-dinu/nlp#1]
- [ ] CS224n course - L9/18
    - [ ] word2vec in pytorch (skipgram, like in L7) - here
    - [ ] [word embeddings](https://pytorch.org/tutorials/beginner/nlp/word_embeddings_tutorial.html)
    - [ ] GloVe
    - [ ] RNNs
    - [ ] LSTMs
    - [ ] seq2seq models
- [ ] relevant papers summary (Tranx, StructVAE)
- [ ] study [AllenNLP](https://allennlp.org/tutorials)
